---
- hosts: instance
  tasks:
    - import_role:
        name: php
      vars:
        php_cli_ini:
          PHP:
            display_errors: 1
          bcmath:
            bcmath.scale: 20
        php_fpm_pools:
          example1:
            user: www-data
            group: www-data
            listen: /run/php/php7.0-fpm-example1.sock
            listen.owner: www-data
            listen.group: www-data
            pm: dynamic
            pm.max_children: 10
            pm.start_servers: 2
            pm.min_spare_servers: 1
            pm.max_spare_servers: 3
          example2:
            user: www-data
            group: www-data
            listen: /run/php/php7.0-fpm-example2.sock
            listen.owner: www-data
            listen.group: www-data
            pm: dynamic
            pm.max_children: 5
            pm.start_servers: 2
            pm.min_spare_servers: 1
            pm.max_spare_servers: 3
